# Generated by Django 3.0.8 on 2020-08-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_details', models.TextField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('stock', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
