# Generated by Django 3.0.8 on 2020-08-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200803_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kid', 'Kids'), ('accesories', 'Accesories'), ('cosmetic', 'Cosmetic')], default='Accesories', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
