# Generated by Django 3.0.8 on 2020-08-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200806_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Accesories', 'Accesories'), ('Cosmetic', 'Cosmetic')], default='Accesories', max_length=50),
        ),
    ]
