# Generated by Django 3.0.8 on 2020-08-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200806_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=0, upload_to='product_images'),
            preserve_default=False,
        ),
    ]
